spring:
  application:
    name: Fsocial-backend
  data:
      mongodb:
        uri: mongodb+srv://phamngoclansr123:x2HBRUVXnbP3sAbv@fsocial.jofkhul.mongodb.net/Fsocial?retryWrites=true&w=majority
  servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: boomkings474@gmail.com
    password: plvy vcph ixtr fxec
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
              
springdoc:
  swagger-ui:
    path=/swagger-ui:
      html:
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: 7d3Qrb/fKptF81DrAevuuvPTwN++BEWzg8mI+PPkkdw=
