spring:
  application:
  name: Fsocial-backend
  data:
      mongodb:
        uri: mongodb+srv://phamngoclansr123:x2HBRUVXnbP3sAbv@fsocial.jofkhul.mongodb.net/Fsocial?retryWrites=true&w=majority
springdoc:
  swagger-ui:
    path=/swagger-ui:
      html:
api:
  prefix: api/v1